//
//  KmeanEntry.h
//  VirtualCoach
//
//  Created by Bi ZORO on 03/03/2016.
//  Copyright © 2016 itzseven. All rights reserved.
//

#import <Foundation/Foundation.h>
#include <geometry.h>
#include <core.h>
#import "Histogram.h"


@interface KmeanEntry : NSObject <NSCoding>

@property (nonatomic) int time;
@property (nonatomic) int maxAngle;
@property (nonatomic) double meanAcceleration;

/*!
 @method generateDataEntryForKmeanFromFirstSpeedVectorsTab:speed1 andSecondSpeedVectorsTab:speed2 betweenInterval:interval andWithImageWidth:width
 @abstract
 Updates the value of the properties maxAngle and meanAcceleration of object KmeanEntry.
 KmeanEntry represents one line on our future file which will stock all lines generated.
 @param speed1
 Set of speed of pixel generated by the optical flow algorithm
 @param speed2
 Set of speed of pixel generated by the optical flow algorithm
 @param interval
 Interval of speed of pixel looked upon as interesting
 @param width
 Width of image using to generate speed of each pixel
 @discussion
 */

- (void)generateDataEntryForKmeanFromFirstSpeedVectorsTab:(vect2darray_t *)speed1 andSecondSpeedVectorsTab:(vect2darray_t *)speed2 betweenInterval:(rect_t)interval andWithImageWidth:(uint16_t)width;


@end
